CREATE TABLE "assumptions" (
	"id" text PRIMARY KEY DEFAULT 'default' NOT NULL,
	"adr_indreby" double precision DEFAULT 1609 NOT NULL,
	"adr_vesterbro" double precision DEFAULT 1195 NOT NULL,
	"adr_noerrebro" double precision DEFAULT 1100 NOT NULL,
	"adr_frederiksberg" double precision DEFAULT 1250 NOT NULL,
	"adr_osterbro" double precision DEFAULT 1202 NOT NULL,
	"adr_amager" double precision DEFAULT 1150 NOT NULL,
	"occ_indreby" double precision DEFAULT 83 NOT NULL,
	"occ_vesterbro" double precision DEFAULT 80 NOT NULL,
	"occ_noerrebro" double precision DEFAULT 78 NOT NULL,
	"occ_frederiksberg" double precision DEFAULT 80 NOT NULL,
	"occ_osterbro" double precision DEFAULT 78 NOT NULL,
	"occ_amager" double precision DEFAULT 78 NOT NULL,
	"room_studio" double precision DEFAULT 0.7 NOT NULL,
	"room_1v" double precision DEFAULT 0.85 NOT NULL,
	"room_2v" double precision DEFAULT 1 NOT NULL,
	"room_3v" double precision DEFAULT 1.4 NOT NULL,
	"room_4v" double precision DEFAULT 1.9 NOT NULL,
	"stand_luksus" double precision DEFAULT 1.15 NOT NULL,
	"stand_god" double precision DEFAULT 1 NOT NULL,
	"stand_aeldre" double precision DEFAULT 0.85 NOT NULL,
	"platform_pct" double precision DEFAULT 15 NOT NULL,
	"rengoring_kr" double precision DEFAULT 300 NOT NULL,
	"naetter_per_booking" double precision DEFAULT 2.875 NOT NULL,
	"admin_pct" double precision DEFAULT 10 NOT NULL,
	"afslag_pct" double precision DEFAULT 3 NOT NULL,
	"conv_fee_pct" double precision DEFAULT 2 NOT NULL,
	"maegler_spar_kr" double precision DEFAULT 80000 NOT NULL,
	"tx_fast_kr" double precision DEFAULT 1850 NOT NULL,
	"tx_pct" double precision DEFAULT 0.6 NOT NULL,
	"beta_worst" double precision DEFAULT 0 NOT NULL,
	"beta_base" double precision DEFAULT 7 NOT NULL,
	"beta_best" double precision DEFAULT 14.8 NOT NULL,
	"lt_indreby" double precision DEFAULT 1500 NOT NULL,
	"lt_osterbro" double precision DEFAULT 1400 NOT NULL,
	"lt_noerrebro" double precision DEFAULT 1300 NOT NULL,
	"lt_vesterbro" double precision DEFAULT 1350 NOT NULL,
	"lt_frederiksberg" double precision DEFAULT 1400 NOT NULL,
	"lt_amager" double precision DEFAULT 1250 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "investors" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text NOT NULL,
	"email" text,
	"phone" text,
	"committed" double precision,
	"deployed" double precision,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "properties" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"address" text NOT NULL,
	"bydel" text NOT NULL,
	"postnr" text,
	"kvm" integer NOT NULL,
	"vaer" integer NOT NULL,
	"bygaar" integer,
	"etage" text,
	"energi" text,
	"udbud" double precision NOT NULL,
	"dage" integer,
	"boligsiden_url" text,
	"fmv" double precision,
	"avm_kvm" double precision,
	"afvigelse" double precision,
	"decil" integer,
	"off_market_pris" double precision,
	"tx_kost" double precision,
	"investeret" double precision,
	"adr" double precision,
	"occ" double precision,
	"brutto_airbnb" double precision,
	"net_airbnb" double precision,
	"ej_skat" double precision,
	"ej_grundskyld" double precision,
	"ej_faelles" double precision,
	"ej_ovrige" double precision,
	"ej_total" double precision,
	"net_cashflow" double precision,
	"cf_yield_best" double precision,
	"cf_yield_base" double precision,
	"cf_yield_worst" double precision,
	"alpha" double precision,
	"profit_worst" double precision,
	"profit_base" double precision,
	"profit_best" double precision,
	"afkast_worst" double precision,
	"afkast_base" double precision,
	"afkast_best" double precision,
	"status" text DEFAULT 'screening' NOT NULL,
	"tilbud_pris" double precision,
	"tilbud_dato" timestamp with time zone,
	"notes" text,
	"prospekt_url" text,
	"image_url" text,
	"investor_id" uuid
);
--> statement-breakpoint
ALTER TABLE "properties" ADD CONSTRAINT "properties_investor_id_investors_id_fk" FOREIGN KEY ("investor_id") REFERENCES "public"."investors"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "properties_status_idx" ON "properties" USING btree ("status");--> statement-breakpoint
CREATE INDEX "properties_bydel_idx" ON "properties" USING btree ("bydel");--> statement-breakpoint
CREATE INDEX "properties_investor_idx" ON "properties" USING btree ("investor_id");